---
- name: Installer Docker sur les VMs
  hosts: web
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository 
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update package list after adding Docker repository
      apt:
        update_cache: yes

    - name: Make sure Docker is installed
      apt:
        name: docker-ce
        state: latest

    - name: Vérifier si le service Docker est disponible
      shell: systemctl is-enabled docker
      register: docker_service_enabled
      ignore_errors: yes

    - name: Ensure the Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
      when: docker_service_enabled.rc == 0

    - name: Échec si Docker n'a pas été trouvé ou installé
      fail:
        msg: "Docker n'a pas été installé correctement ou le service n'est pas disponible."
      when: docker_service_enabled.rc != 0
