---
- name: Installer Docker sur les VMs
  hosts: web
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository 
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update package list after adding Docker repository
      apt:
        update_cache: yes

    - name: Make sure Docker is installed
      apt:
        name: docker-ce
        state: latest

  #  - name: Ajouter l'utilisateur Ansible au groupe Docker
  #    user:
  #      name: "{{ ansible_user }}"
  #      groups: docker
  #      append: yes

  #  - name: Ajuster les permissions du socket Docker
  #    file:
  #      path: /var/run/docker.sock
  #      state: file
  #      owner: root
  #      group: docker
  #      mode: '0660'

    - name: Reload docker systemd daemon
      command: systemctl daemon-reload
     # ansible.builtin.systemd_service:
     #   daemon_reload: true

    - name: Ensure the Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

