---
- name: Setup Web Server
#  hosts: web
  hosts: webserver
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: 'yes'
    - name: Copy Nginx configuration
      ansible.builtin.copy:
        src: /etc/nginx/nginx.conf 
        dest: /etc/nginx/nginx.conf 
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
        backup: 'yes'
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
